name: Build
on:
  pull_request:
    types:
      - synchronize
      - opened
      - labeled
    paths-ignore:
      - ".github/**"
      - "docs/**"
  push:
    branches: [livekit, full-mesh]
    paths-ignore:
      - ".github/**"
      - "docs/**"
jobs:
  build_element_call:
    uses: ./.github/workflows/element-call.yaml
    with:
      vite_app_version: ${{ github.event.release.tag_name || github.sha }}
    secrets:
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
