name: Lint, format & type check
on:
  pull_request: {}
jobs:
  prettier:
    name: Lint, format & type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Yarn cache
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          cache: "yarn"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: "yarn install --frozen-lockfile"
      - name: Prettier
        run: "yarn run prettier:check"
      - name: i18n
        run: "yarn run i18n:check"
      - name: ESLint
        run: "yarn run lint:eslint"
      - name: Type check
        run: "yarn run lint:types"
      - name: Dead code analysis
        run: "yarn run lint:knip"
