name: Upload translation files to Localazy
on:
  push:
    branches:
      - livekit
    paths-ignore:
      - ".github/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Upload
        uses: localazy/upload@27e6b5c0fddf4551596b42226b1c24124335d24a # v1
        with:
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
