name: Download translation files from Localazy
on:
  workflow_dispatch:
    secrets:
      ELEMENT_BOT_TOKEN:
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          cache: "yarn"
          node-version-file: ".node-version"

      - name: Install Deps
        run: "yarn install --frozen-lockfile"

      - name: Prune i18n
        run: "rm -R locales"

      - name: Download translation files
        uses: localazy/download@0a79880fb66150601e3b43606fab69c88123c087 # v1.1.0
        with:
          groups: "-p includeSourceLang:true"

      - name: Fix the owner of the downloaded files
        run: "sudo chown runner:docker -R locales"

      - name: Prettier
        run: yarn prettier:format

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          token: ${{ secrets.ELEMENT_BOT_TOKEN }}
          branch: actions/localazy-download
          delete-branch: true
          title: Localazy Download
          commit-message: Translations updates
          labels: |
            T-Task

      - name: Enable automerge
        run: gh pr merge --merge --auto "$PR_NUMBER"
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
